-- Identity Resolution: links and proposals tables.
-- identity.input and identity.person are managed by dbt (VIEW and table).
-- This migration creates tables that dbt writes to and that operators interact with directly.

-- ============================================================
-- identity.links — operator decisions: profile ↔ person bindings
-- Append-only. Each row = "at time X, profile Y was linked/unlinked to person Z"
-- ============================================================

CREATE TABLE IF NOT EXISTS identity.links
(
    id                  UUID DEFAULT generateUUIDv7(),
    insight_tenant_id   String,
    person_id           UUID,
    source_type         LowCardinality(String),
    profile_id          Nullable(String),              -- NULL = unlink
    action              LowCardinality(String) DEFAULT 'link',  -- link, unlink
    reason              String DEFAULT '',              -- new_person, merge, split, same_email, operator_decision
    created_by          String DEFAULT '',
    created_at          DateTime64(3, 'UTC') DEFAULT now64(3)
)
ENGINE = MergeTree
ORDER BY (insight_tenant_id, person_id, source_type, created_at);

-- ============================================================
-- identity.proposals — generated by dbt, reviewed by operator
-- Append-only staging table. dbt writes proposals, operator reads.
-- ============================================================

CREATE TABLE IF NOT EXISTS identity.proposals
(
    id                  UUID DEFAULT generateUUIDv7(),
    insight_tenant_id   String,
    proposal_type       LowCardinality(String),         -- new_profile, email_match, deactivation
    status              LowCardinality(String) DEFAULT 'pending',
    source_type         LowCardinality(String),
    profile_id          String DEFAULT '',
    field_type          LowCardinality(String) DEFAULT '',
    field_value         String DEFAULT '',
    matched_source_type LowCardinality(String) DEFAULT '',
    matched_profile_id  String DEFAULT '',
    match_reason        String DEFAULT '',
    confidence          Float32 DEFAULT 1.0,
    _synced_at          DateTime64(3, 'UTC') DEFAULT now64(3)
)
ENGINE = MergeTree
ORDER BY (insight_tenant_id, status, proposal_type, source_type, profile_id, _synced_at);
